//
// Created by dylan on 5/2/22.
//

#ifndef BATTLE_OF_PLEIADES_DEFS_H
#define BATTLE_OF_PLEIADES_DEFS_H

#define SCREEN_WIDTH 1920//1440
#define SCREEN_HEIGHT 1080//1080

#define MAX_KEYBOARD_KEYS 500

#define UNIT_DEGREE_IN_RADIANS 0.0174533

#define PLAYER_MAX_SPEED 8

#define MAX_FPS 60

#define ACCELERATION_MULT 20

#define DRAG_MULT 1

#define DURATION_PER_FRAME 1 / MAX_FPS

#define MAX_SND_CHANNELS 8

#define FPS 60

enum {
    CH_ANY = -1,
    CH_PLAYER,
    CH_ALIEN_FIRE,
};

enum {
    SND_PLAYER_FIRE,
    SND_ALIEN_FIRE,
    SND_PLAYER_DIE,
    SND_ALIEN_DIE,
    SND_MAX,
};

#endif //BATTLE_OF_PLEIADES_DEFS_H
