//
// Created by dylan on 5/2/22.
//

#ifndef BATTLE_OF_PLEIADES_DEFS_H
#define BATTLE_OF_PLEIADES_DEFS_H

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720

#define MAX_KEYBOARD_KEYS 500

#define UNIT_DEGREE_IN_RADIANS 0.0174533

#define PLAYER_MAX_SPEED 8

#define MAX_FPS 60

#define ACCELERATION_MULT 20

#define DRAG_MULT 1

#define DURATION_PER_FRAME 1 / MAX_FPS

#endif //BATTLE_OF_PLEIADES_DEFS_H
